### ISSUE TITLE
Add environment variables for database configuration

### ISSUE THREAD

**Issue by AndrejsPon00** [TSI-Projects/group-project#23]
Please define the following environment variables in the project configuration to allow database connection:

- DB_NAME: The name of the database
- DB_USERNAME: The username for the database connection
- DB_PASSWORD: The password for the database connection

**Comment by SkinonikS** [comment]
https://github.com/TSI-Projects/group-project/blob/e61de95082dfedd3b6cf77d3629586b6fd543e74/devops/helm-charts/go-server/templates/deployment.yaml#L25-L50

**Comment by AndrejsPon00** [comment]
My bad, I didn't see it :D
https://github.com/TSI-Projects/group-project/blob/main/devops/helm-charts/go-server/templates/deployment.yaml
